spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ThesisPulse
    username: root
    password: rootrootroot
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 500000
      max-lifetime: 540000
      connection-timeout: 60000
      connection-test-query: SELECT 1
  mail:
    # 配置 SMTP 服务器地址
    host: smtp.office365.com
    # 发送者邮箱
    username: 
    # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
    password: 
    # 端口号465或587
    port: 587
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    properties:
      from: 
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      password: 131598
  ai:
    openai:
      api-key: sk-ogYkIdwdnkad8Fa47668828Bb290a51544b
      base-url: https://api.openai.com